---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fhor9931/public_html
    - /bin/cp -R /home/fhor9931/osso-website.portfolio-taglialatela.fr $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader
    - yarn install
    - yarn build
    - php bin/console d:m:m
    - php bin/console cache:clear --env=prod
    - php bin/console cache:warmup

  main_domain: portfolio-taglialatela.fr
  on_start:
    - create_subdomain:
        name: www
    - create_subdomain:
        name: osso-website
  sub_domains:
    - osso-website.portfolio-taglialatela.fr
