#!/usr/bin/bash
rm -Rf vendor/
#composer install --ignore-platform-reqs
composer install --no-dev --optimize-autoloader
yarn install
composer dump-env prod
APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
yarn build
